Repository TeamHarTex/HarTex, pull requests merged in 2023-09, with the labels that each got.

#1404 Fix: Handlebars in Bors
  bors/hartex-bors-website/src/main.rs
Labels: Bors: Bugfix

#1416 `large` Field in Guild Entity
  api-backend/Cargo.lock
  buildsystem/Cargo.lock
  discord-frontend/hartex-discord-entitycache-entities/src/guild.rs
  discord-frontend/hartex-discord-entitycache-repositories/src/guild.rs
Labels: Bot: Enhancement

#1417 Add Server Flags Field Stub
  discord-frontend/hartex-discord-commands/src/utilities/info/info_server.rs
  localization/locales/en-GB/discord-frontend/commands/utilities-plugin.ftl
Labels: Bot: Enhancement

#1418 `/info server`: Large Server Flag
  discord-frontend/hartex-discord-commands/src/utilities/info/info_server.rs
  localization/locales/en-GB/discord-frontend/commands/utilities-plugin.ftl
Labels: Bot: Enhancement

#1421 Bors: Use Exposed `DirectorySourceOptions`
  bors/hartex-bors-website/src/main.rs
Labels: Bors: Enhancement

#1428 Commands: Update Information and Implementation
  discord-frontend/hartex-discord-commands/src/general/contributors.rs
  discord-frontend/hartex-discord-commands/src/utilities/info/info_bot.rs
Labels: Bot: Enhancement

#1433 Backend: Fix Clippy Lints
  api-backend/hartex-backend-routes-v1/src/bors.rs
  api-backend/hartex-backend-routes-v1/src/uptime.rs
Labels: Backend: Enhancement

#1434 implement localize for DefaultMessageNotificationLevel
  rust-utilities/Cargo.lock
  rust-utilities/hartex-discord-utils/Cargo.toml
  rust-utilities/hartex-discord-utils/src/localizable/discord/guild.rs
Labels: Utilities: Enhancement, Localization: Enhancement

#1435 Update zh-TW translation
  localization/locales/zh-TW/discord-frontend/commands/utilities-plugin.ftl
  localization/locales/zh-TW/discord-frontend/guild.ftl
Labels: Localization: Enhancement

#1436 `/info server`: Add Default Message Notification Level
  discord-frontend/hartex-discord-commands/src/utilities/info/info_server.rs
  discord-frontend/hartex-discord-entitycache-entities/src/guild.rs
  discord-frontend/hartex-discord-entitycache-repositories/src/guild.rs
  localization/locales/en-GB/discord-frontend/commands/utilities-plugin.ftl
Labels: Bot: Enhancement

#1440 Guild Entity: Add `explicit_content_filter`
  discord-frontend/hartex-discord-entitycache-entities/src/guild.rs
  discord-frontend/hartex-discord-entitycache-repositories/src/guild.rs
Labels: Bot: Enhancement

#1444 Entity Macro: Extract `twilight-model` Archive
  .gitignore
  discord-frontend/Cargo.lock
  discord-frontend/hartex-discord-entitycache-macros/Cargo.toml
  discord-frontend/hartex-discord-entitycache-macros/build.rs
  rust-utilities/Cargo.lock
Labels: Bot: Enhancement

#1448 Entity Macro: Prepare for Module Tree Generation
  discord-frontend/hartex-discord-entitycache-macros/Cargo.toml
  discord-frontend/hartex-discord-entitycache-macros/build.rs
Labels: Bot: Enhancement

#1449 Entity Macro: Generate Module Tree
  discord-frontend/hartex-discord-entitycache-macros/build.rs
Labels: Bot: Enhancement

#1453 Entity Macro: More Infrastructure
  .idea/inspectionProfiles/Project_Default.xml
  discord-frontend/hartex-discord-entitycache-macros/build.rs
  discord-frontend/hartex-discord-entitycache-macros/src/entity.rs
  discord-frontend/hartex-discord-entitycache-macros/src/entity_deprecated.rs
  discord-frontend/hartex-discord-entitycache-macros/src/lib.rs
  rust-utilities/Cargo.lock
Labels: Bot: Enhancement

#1455 Entity Macro: Obtain Struct Metadata If Exist
  discord-frontend/hartex-discord-entitycache-macros/src/entity.rs
Labels: Bot: Enhancement

#1456 Entity Macro: Get Fields
  discord-frontend/hartex-discord-entitycache-macros/build.rs
  discord-frontend/hartex-discord-entitycache-macros/src/entity.rs
Labels: Bot: Enhancement

#1458 Entity Macro: Get Include Fields
  discord-frontend/hartex-discord-entitycache-macros/src/entity.rs
  rust-utilities/Cargo.lock
Labels: Bot: Enhancement

#1463 Make `exclude` and `include` Fields Mutual Exclusive
  discord-frontend/hartex-discord-entitycache-macros/src/entity.rs
Labels: Bot: Enhancement

#1465 Mutual Exclusive Stuff
  discord-frontend/hartex-discord-entitycache-macros/src/entity.rs
  discord-frontend/hartex-discord-entitycache-macros/src/lib.rs
Labels: Bot: Enhancement

#1469 Fix Compiler Errors
  discord-frontend/hartex-discord-entitycache-macros/src/entity.rs
Labels: Bot: Enhancement, Bot: Bugfix

#1472 Update Entity Macro
  discord-frontend/Cargo.lock
  discord-frontend/hartex-discord-entitycache-macros/Cargo.toml
  discord-frontend/hartex-discord-entitycache-macros/src/entity.rs
Labels: Bot: Enhancement

#1474 Emit Warnings for Unknown Fields
  discord-frontend/hartex-discord-entitycache-macros/src/entity.rs
Labels: Bot: Enhancement

#1480 Bump Minimum Rust Compiler Version
  api-backend/hartex-backend-driver/Cargo.toml
  api-backend/hartex-backend-models-v1/Cargo.toml
  api-backend/hartex-backend-models/Cargo.toml
  api-backend/hartex-backend-ratelimiter/Cargo.toml
  api-backend/hartex-backend-routes-v1/Cargo.toml
  api-backend/hartex-backend-status-util/Cargo.toml
  bors/hartex-bors-commands/Cargo.toml
  bors/hartex-bors-core/Cargo.toml
  bors/hartex-bors-database/Cargo.toml
  bors/hartex-bors-driver/Cargo.toml
  bors/hartex-bors-github/Cargo.toml
  bors/hartex-bors-permissions/Cargo.toml
  bors/hartex-bors-website/Cargo.toml
  buildsystem/hartexbuild-driver/Cargo.toml
  buildsystem/hartexbuild-hartexfile/Cargo.toml
  discord-frontend/hartex-discord-cdn/Cargo.toml
  discord-frontend/hartex-discord-commands-core/Cargo.toml
  discord-frontend/hartex-discord-commands-macros/Cargo.toml
  discord-frontend/hartex-discord-commands-manager/Cargo.toml
  discord-frontend/hartex-discord-commands-test/Cargo.toml
  discord-frontend/hartex-discord-commands/Cargo.toml
  discord-frontend/hartex-discord-configuration-manifest/Cargo.toml
  discord-frontend/hartex-discord-configuration-test/Cargo.toml
  discord-frontend/hartex-discord-core/Cargo.toml
  discord-frontend/hartex-discord-entitycache-cacheupdaters/Cargo.toml
  discord-frontend/hartex-discord-entitycache-core/Cargo.toml
  discord-frontend/hartex-discord-entitycache-entities/Cargo.toml
  discord-frontend/hartex-discord-entitycache-macros/Cargo.toml
  discord-frontend/hartex-discord-entitycache-repositories/Cargo.toml
  discord-frontend/hartex-discord-entitycache-test/Cargo.toml
  discord-frontend/hartex-discord-leader/Cargo.toml
  discord-frontend/hartex-discord-worker/Cargo.toml
  localization/hartex-localization-core/Cargo.toml
  localization/hartex-localization-macros/Cargo.toml
  localization/hartex-localization-test/Cargo.toml
  rust-utilities/hartex-discord-utils/Cargo.toml
  rust-utilities/hartex-errors/Cargo.toml
  rust-utilities/hartex-kafka-utils/Cargo.toml
  rust-utilities/hartex-log/Cargo.toml
Labels: Bot: Enhancement

#1481 Add Deny Lints
  discord-frontend/hartex-discord-cdn/src/lib.rs
Labels: Bot: Enhancement

#1482 Initialize Building Struct Declaration
  discord-frontend/hartex-discord-entitycache-macros/src/entity.rs
Labels: Bot: Enhancement

#1493 Construct List of Fields to Include
  discord-frontend/hartex-discord-entitycache-macros/src/entity.rs
Labels: Bot: Enhancement
