Repository TeamHarTex/HarTex, pull requests merged in 2023-07, with the labels that each got.

#1101 Discord Frontend: Migrate to PostgreSQL
  api-backend/hartex-backend-routes-v1/src/uptime.rs
  database-queries/start-timestamp/insert-into-on-conflict-update.sql
  database-queries/start-timestamp/select-by-component.sql
  discord-frontend/Cargo.lock
  discord-frontend/hartex-discord-commands-macros/src/commandmetadata.rs
  discord-frontend/hartex-discord-commands-manager/src/commands/mod.rs
  discord-frontend/hartex-discord-commands-manager/src/main.rs
  discord-frontend/hartex-discord-commands-manager/src/model/option/mod.rs
  discord-frontend/hartex-discord-configuration-manifest/src/ranks.rs
  discord-frontend/hartex-discord-configuration-test/tests/deserialize_test.rs
  discord-frontend/hartex-discord-entitycache-entities/src/lib.rs
  discord-frontend/hartex-discord-worker/Cargo.toml
  discord-frontend/hartex-discord-worker/src/eventcallback.rs
Labels: Bot: Enhancement, Bot: Breaking Change, Backend: Enhancement

#1102 Discord Frontend: Remove Database Flag From `core`
  discord-frontend/Cargo.lock
  discord-frontend/hartex-discord-core/Cargo.toml
  discord-frontend/hartex-discord-leader/Cargo.toml
Labels: Bot: Enhancement

#1103 Buildsystem: Support Multiple Projects for Commands
  buildsystem/hartexbuild-driver/src/commands/build.rs
  buildsystem/hartexbuild-driver/src/commands/lint.rs
  buildsystem/hartexbuild-driver/src/commands/test.rs
  buildsystem/hartexbuild-driver/src/main.rs
Labels: Buildsystem: Enhancement, Buildsystem: Feature

#1105 Bors: Tweak Parsing to Support Parameters
  bors/hartex-bors-commands/src/lib.rs
  bors/hartex-bors-commands/src/parser.rs
  bors/hartex-bors-driver/src/event.rs
Labels: Bors: Enhancement

#1106 Bors: Try Optionally Use Parent Commit
  bors/hartex-bors-commands/src/commands/try.rs
  bors/hartex-bors-driver/src/event.rs
Labels: Bors: Enhancement, Bors: Feature

#1107 Discord Frontend: Stub for Serverinfo Command
  discord-frontend/hartex-discord-commands/src/lib.rs
  discord-frontend/hartex-discord-commands/src/utilities/mod.rs
  discord-frontend/hartex-discord-commands/src/utilities/serverinfo.rs
Labels: Bot: Enhancement, Bot: Feature

#1110 Discord Frontend: Implement `Command` Trait
  discord-frontend/hartex-discord-commands/src/utilities/serverinfo.rs
Labels: Bot: Enhancement, Bot: Feature

#1118 Localization Infrastructure for Serverinfo
  discord-frontend/hartex-discord-commands/src/utilities/serverinfo.rs
  localization/locales/en-GB/discord-frontend/commands/utilities-plugin.ftl
Labels: Localization: Enhancement

#1122 Cache: Add Guild Name
  database-queries/start-timestamp/insert-into-on-conflict-update.sql
  discord-frontend/hartex-discord-commands/src/utilities/serverinfo.rs
  discord-frontend/hartex-discord-entitycache-cacheupdaters/src/guild_create.rs
  discord-frontend/hartex-discord-entitycache-entities/src/guild.rs
  discord-frontend/hartex-discord-entitycache-repositories/src/guild.rs
  docker/docker-compose.yml
  localization/locales/en-GB/discord-frontend/commands/utilities-plugin.ftl
Labels: Bot: Enhancement

#1143 Temporarily Revert SQLx 0.7 Upgrade
  api-backend/Cargo.lock
  api-backend/hartex-backend-models-v1/Cargo.toml
  api-backend/hartex-backend-routes-v1/Cargo.toml
  bors/Cargo.lock
  bors/hartex-bors-database/Cargo.toml
  discord-frontend/Cargo.lock
  discord-frontend/hartex-discord-worker/Cargo.toml
Labels: Bot: Bugfix

#1146 Remove `hartex-eyre` from Backend
  .idea/HarTex-rust-discord-bot.iml
  api-backend/Cargo.lock
  api-backend/hartex-backend-driver/Cargo.toml
  api-backend/hartex-backend-driver/src/main.rs
  api-backend/hartex-backend-models-v1/src/uptime.rs
  api-backend/hartex-backend-routes-v1/src/uptime.rs
  rust-utilities/Cargo.lock
  rust-utilities/Cargo.toml
  rust-utilities/hartex-errors/Cargo.toml
  rust-utilities/hartex-errors/src/dotenv.rs
  rust-utilities/hartex-errors/src/lib.rs
Labels: Backend: Breaking Change, Backend: Enhancement

#1150 Bors: Switch to Miette
  api-backend/Cargo.lock
  bors/Cargo.lock
  bors/hartex-bors-driver/Cargo.toml
  bors/hartex-bors-driver/src/main.rs
  buildsystem/Cargo.lock
  discord-frontend/Cargo.lock
  localization/Cargo.lock
  rust-utilities/Cargo.lock
Labels: Bors: Breaking Change, Bors: Enhancement

#1151 Buildsystem: Use Miette
  buildsystem/Cargo.lock
  buildsystem/hartexbuild-driver/Cargo.toml
  buildsystem/hartexbuild-driver/src/cmdline.rs
  buildsystem/hartexbuild-driver/src/commands/build.rs
  buildsystem/hartexbuild-driver/src/commands/lint.rs
  buildsystem/hartexbuild-driver/src/commands/test.rs
  buildsystem/hartexbuild-driver/src/main.rs
  buildsystem/hartexbuild-hartexfile/Cargo.toml
  buildsystem/hartexbuild-hartexfile/src/spec/project.rs
Labels: Buildsystem: Enhancement

#1159 Buildsystem: Migrate More To Miette
  buildsystem/Cargo.lock
  buildsystem/hartexbuild-driver/Cargo.toml
  buildsystem/hartexbuild-driver/src/commands/build.rs
  buildsystem/hartexbuild-driver/src/commands/lint.rs
  buildsystem/hartexbuild-driver/src/commands/test.rs
  buildsystem/hartexbuild-hartexfile/Cargo.toml
  buildsystem/hartexbuild-hartexfile/src/lib.rs
  buildsystem/hartexbuild-hartexfile/src/spec/project.rs
  rust-utilities/hartex-errors/src/buildsystem.rs
  rust-utilities/hartex-errors/src/lib.rs
Labels: Buildsystem: Enhancement

#1164 Bors: Migrate More to Miette
  api-backend/Cargo.lock
  api-backend/hartex-backend-models-v1/Cargo.toml
  api-backend/hartex-backend-routes-v1/Cargo.toml
  bors/Cargo.lock
  bors/hartex-bors-commands/Cargo.toml
  bors/hartex-bors-commands/src/commands/approve.rs
  bors/hartex-bors-commands/src/commands/approve_cancel.rs
  bors/hartex-bors-commands/src/commands/ping.rs
  bors/hartex-bors-commands/src/commands/try.rs
  bors/hartex-bors-commands/src/commands/try_cancel.rs
  bors/hartex-bors-commands/src/parser.rs
  bors/hartex-bors-commands/src/permissions.rs
  bors/hartex-bors-core/Cargo.toml
  bors/hartex-bors-core/src/lib.rs
  bors/hartex-bors-core/src/models.rs
  bors/hartex-bors-database/Cargo.toml
  bors/hartex-bors-database/src/client.rs
  bors/hartex-bors-database/src/lib.rs
  bors/hartex-bors-database/src/select_enqueued_pr.rs
  bors/hartex-bors-database/src/select_pr.rs
  bors/hartex-bors-database/src/select_workflow.rs
  bors/hartex-bors-driver/src/event.rs
  bors/hartex-bors-driver/src/queue.rs
  bors/hartex-bors-driver/src/workflows.rs
  bors/hartex-bors-github/Cargo.toml
  bors/hartex-bors-github/src/lib.rs
  bors/hartex-bors-github/src/operations.rs
  bors/hartex-bors-github/src/repositories.rs
  bors/hartex-bors-permissions/Cargo.toml
  bors/hartex-bors-permissions/src/lib.rs
  bors/hartex-bors-permissions/src/permissions.rs
Labels: Bors: Breaking Change, Bors: Enhancement

#1171 Bors: Fix Compilation Errors
  bors/hartex-bors-commands/src/parser.rs
  bors/hartex-bors-driver/src/event.rs
  bors/hartex-bors-driver/src/main.rs
  bors/hartex-bors-driver/src/workflows.rs
Labels: Bors: Enhancement

#1173 Discord Frontend: Migrate to Miette
  api-backend/Cargo.lock
  api-backend/hartex-backend-driver/src/main.rs
  bors/hartex-bors-commands/src/commands/approve.rs
  bors/hartex-bors-commands/src/commands/approve_cancel.rs
  bors/hartex-bors-commands/src/commands/try_cancel.rs
  bors/hartex-bors-commands/src/lib.rs
  bors/hartex-bors-commands/src/parser.rs
  bors/hartex-bors-core/src/lib.rs
  bors/hartex-bors-core/src/models.rs
  bors/hartex-bors-core/src/queue.rs
  bors/hartex-bors-database/src/client.rs
  bors/hartex-bors-database/src/entity/pull_request.rs
  bors/hartex-bors-database/src/lib.rs
  bors/hartex-bors-database/src/migration/m_20230613_1838_create_enqueued.rs
  bors/hartex-bors-database/src/select_enqueued_pr.rs
  bors/hartex-bors-database/src/select_pr.rs
  bors/hartex-bors-driver/src/event.rs
  bors/hartex-bors-driver/src/main.rs
  bors/hartex-bors-driver/src/workflows.rs
  bors/hartex-bors-github/src/lib.rs
  bors/hartex-bors-github/src/repositories.rs
  bors/hartex-bors-permissions/src/permissions.rs
  buildsystem/Cargo.lock
  discord-frontend/Cargo.lock
  discord-frontend/hartex-discord-commands-core/Cargo.toml
  discord-frontend/hartex-discord-commands-core/src/traits.rs
  discord-frontend/hartex-discord-commands-macros/src/commandmetadata.rs
  discord-frontend/hartex-discord-commands/Cargo.toml
  discord-frontend/hartex-discord-commands/src/general/about.rs
  discord-frontend/hartex-discord-commands/src/general/contributors.rs
  discord-frontend/hartex-discord-commands/src/general/latency.rs
  discord-frontend/hartex-discord-commands/src/general/uptime.rs
  discord-frontend/hartex-discord-commands/src/utilities/serverinfo.rs
  discord-frontend/hartex-discord-entitycache-macros/src/entity.rs
  discord-frontend/hartex-discord-leader/Cargo.toml
  discord-frontend/hartex-discord-leader/src/inbound.rs
  discord-frontend/hartex-discord-leader/src/main.rs
  discord-frontend/hartex-discord-leader/src/queue.rs
  discord-frontend/hartex-discord-leader/src/shards.rs
  discord-frontend/hartex-discord-worker/Cargo.toml
  discord-frontend/hartex-discord-worker/src/entitycache.rs
  discord-frontend/hartex-discord-worker/src/eventcallback.rs
  discord-frontend/hartex-discord-worker/src/interaction.rs
  discord-frontend/hartex-discord-worker/src/main.rs
  localization/Cargo.lock
  localization/hartex-localization-core/Cargo.toml
  localization/hartex-localization-core/src/lib.rs
  localization/hartex-localization-macros/src/expand_bundle_get.rs
  localization/hartex-localization-macros/src/expand_bundle_get_args.rs
  rust-utilities/Cargo.lock
  rust-utilities/hartex-errors/src/buildsystem.rs
Labels: Bot: Enhancement

#1181 Serverinfo: Send Basic Response
  api-backend/hartex-backend-models-v1/src/uptime.rs
  api-backend/hartex-backend-routes-v1/src/uptime.rs
  discord-frontend/Cargo.lock
  discord-frontend/hartex-discord-commands-spec/general-plugin/about.json
  discord-frontend/hartex-discord-commands-spec/general-plugin/uptime.json
  discord-frontend/hartex-discord-commands-spec/utilities-plugin/serverinfo.json
  discord-frontend/hartex-discord-commands/Cargo.toml
  discord-frontend/hartex-discord-commands/src/utilities/serverinfo.rs
  discord-frontend/hartex-discord-worker/src/interaction.rs
  rust-utilities/Cargo.lock
Labels: Bot: Enhancement, Bot: Feature

#1187 Serverinfo: Update Displayed Information
  discord-frontend/hartex-discord-cdn/src/lib.rs
  discord-frontend/hartex-discord-commands/src/utilities/serverinfo.rs
  localization/locales/en-GB/discord-frontend/commands/utilities-plugin.ftl
Labels: Bot: Enhancement

#1192 Serverinfo: Further Work
  discord-frontend/Cargo.lock
  discord-frontend/hartex-discord-commands/Cargo.toml
  discord-frontend/hartex-discord-commands/src/utilities/serverinfo.rs
  discord-frontend/hartex-discord-core/Cargo.toml
  localization/locales/en-GB/discord-frontend/commands/utilities-plugin.ftl
Labels: Bot: Enhancement

#1208 Allow Outbound Commands
  RELEASES.md
  api-backend/hartex-backend-models-v1/Cargo.toml
  api-backend/hartex-backend-routes-v1/Cargo.toml
  bors/hartex-bors-database/Cargo.toml
  discord-frontend/hartex-discord-leader/src/kafka.rs
  discord-frontend/hartex-discord-leader/src/main.rs
  discord-frontend/hartex-discord-worker/Cargo.toml
  localization/locales/en-GB/discord-frontend/commands/utilities-plugin.ftl
Labels: Bot: Enhancement

#1210 Invoke Request Guild Members Command
  api-backend/Cargo.lock
  bors/Cargo.lock
  discord-frontend/Cargo.lock
  discord-frontend/hartex-discord-commands/src/utilities/serverinfo.rs
  discord-frontend/hartex-discord-core/src/lib.rs
  discord-frontend/hartex-discord-entitycache-macros/src/entity.rs
  discord-frontend/hartex-discord-leader/Cargo.toml
  discord-frontend/hartex-discord-leader/src/kafka.rs
  discord-frontend/hartex-discord-leader/src/main.rs
  discord-frontend/hartex-discord-worker/src/eventcallback.rs
  discord-frontend/hartex-discord-worker/src/main.rs
  rust-utilities/hartex-log/src/lib.rs
Labels: Bot: Enhancement

#1214 Serverinfo: Add `verbose` Option
  discord-frontend/hartex-discord-commands-spec/utilities-plugin/serverinfo.json
Labels: Bot: Enhancement, Bot: Breaking Change

#1215 Teddy: Add `zh_CN` Translations to Command Spec
  discord-frontend/hartex-discord-commands-spec/utilities-plugin/serverinfo.json
Labels: Localization: Enhancement

#1218 Teddy: add remaining zh_CN translations
  .idea/inspectionProfiles/Project_Default.xml
  localization/locales/zh-CN/discord-frontend/commands/utilities-plugin.ftl
Labels: Localization: Enhancement

#1219 Serverinfo: Bail Out If Server Specified Temporarily
  discord-frontend/hartex-discord-commands-spec/utilities-plugin/serverinfo.json
  discord-frontend/hartex-discord-commands/src/utilities/serverinfo.rs
  discord-frontend/hartex-discord-entitycache-repositories/src/member.rs
Labels: Bot: Enhancement, Bot: Breaking Change

#1220 Fix Compiler Error
  discord-frontend/hartex-discord-commands/src/utilities/serverinfo.rs
Labels: Bot: Enhancement

#1222 Serverinfo: Add `verbose` Filter
  RELEASES.md
  discord-frontend/hartex-discord-commands/src/utilities/serverinfo.rs
Labels: Bot: Enhancement, Bot: Breaking Change

#1223 Serverinfo: Make Unsupported Message Localizable
  discord-frontend/hartex-discord-commands/src/utilities/serverinfo.rs
  localization/locales/en-GB/discord-frontend/commands/utilities-plugin.ftl
Labels: Bot: Enhancement

#1224 Update CI
  .github/workflows/lints.yml
  .github/workflows/tests.yml
  api-backend/hartex-backend-status-util/src/lib.rs
  bors/hartex-bors-core/src/models.rs
  buildsystem/hartexbuild-driver/src/cmdline.rs
  buildsystem/hartexbuild-driver/src/commands/build.rs
  buildsystem/hartexbuild-driver/src/commands/lint.rs
  buildsystem/hartexbuild-driver/src/commands/test.rs
  buildsystem/hartexbuild-driver/src/main.rs
Labels: Buildsystem: Enhancement, CI: Enhancement, Backend: Enhancement, Bors: Enhancement

#1226 Make Clippy Happy
  api-backend/clippy.toml
  api-backend/hartex-backend-driver/src/main.rs
  api-backend/hartex-backend-models-v1/src/bors.rs
  api-backend/hartex-backend-models-v1/src/uptime.rs
  api-backend/hartex-backend-ratelimiter/src/error.rs
  api-backend/hartex-backend-ratelimiter/src/limitable.rs
  api-backend/hartex-backend-ratelimiter/src/registry.rs
  api-backend/hartex-backend-ratelimiter/src/state.rs
  api-backend/hartex-backend-routes-v1/src/bors.rs
  api-backend/hartex-backend-routes-v1/src/uptime.rs
  bors/clippy.toml
  bors/hartex-bors-commands/src/commands/approve.rs
  bors/hartex-bors-commands/src/commands/approve_cancel.rs
  bors/hartex-bors-commands/src/commands/ping.rs
  bors/hartex-bors-commands/src/commands/try.rs
  bors/hartex-bors-commands/src/commands/try_cancel.rs
  bors/hartex-bors-commands/src/lib.rs
  bors/hartex-bors-commands/src/parser.rs
  bors/hartex-bors-commands/src/permissions.rs
  bors/hartex-bors-database/src/client.rs
  bors/hartex-bors-database/src/lib.rs
  bors/hartex-bors-database/src/migration/m_20230527_2254_create_build.rs
  bors/hartex-bors-database/src/migration/m_20230529_2203_create_workflow.rs
  bors/hartex-bors-database/src/migration/m_20230604_1237_create_repository.rs
  bors/hartex-bors-database/src/migration/m_20230605_2015_create_pr.rs
  bors/hartex-bors-database/src/migration/m_20230608_2047_create_approve_build.rs
  bors/hartex-bors-database/src/migration/m_20230613_1838_create_enqueued.rs
  bors/hartex-bors-driver/src/event.rs
  bors/hartex-bors-driver/src/process.rs
  bors/hartex-bors-driver/src/queue.rs
  bors/hartex-bors-driver/src/workflows.rs
  bors/hartex-bors-github/src/lib.rs
  bors/hartex-bors-github/src/messages.rs
  bors/hartex-bors-github/src/operations.rs
  bors/hartex-bors-github/src/webhook.rs
  bors/hartex-bors-permissions/src/lib.rs
  bors/hartex-bors-permissions/src/permissions.rs
  bors/hartex-bors-website/src/main.rs
  bors/hartex-bors-website/src/queue.rs
Labels: Backend: Enhancement, Bors: Enhancement

#1227 Teddy: Update `zh_CN`
  localization/locales/zh-CN/discord-frontend/commands/utilities-plugin.ftl
Labels: Localization: Enhancement

#1229 Add `info` Unlocalized Command Specification
  discord-frontend/hartex-discord-commands-spec/utilities-plugin/info.json
  discord-frontend/hartex-discord-commands/src/utilities/serverinfo.rs
Labels: Bot: Enhancement

#1233 Add `info server` Subcommand Specification
  discord-frontend/hartex-discord-commands-spec/utilities-plugin/info.json
Labels: Bot: Enhancement, Bot: Breaking Change

#1234 Serverinfo: Changed As `info server`
  discord-frontend/hartex-discord-commands/src/utilities/info/info_server.rs
  discord-frontend/hartex-discord-commands/src/utilities/info/mod.rs
  discord-frontend/hartex-discord-commands/src/utilities/mod.rs
  discord-frontend/hartex-discord-commands/src/utilities/serverinfo.rs
  discord-frontend/hartex-discord-worker/src/eventcallback.rs
  discord-frontend/hartex-discord-worker/src/interaction.rs
  localization/locales/en-GB/discord-frontend/commands/utilities-plugin.ftl
  localization/locales/zh-CN/discord-frontend/commands/utilities-plugin.ftl
  localization/locales/zh-TW/discord-frontend/commands/utilities-plugin.ftl
Labels: Bot: Enhancement, Bot: Breaking Change

#1235 Info: Add `bot` Subcommand
  discord-frontend/hartex-discord-commands-spec/utilities-plugin/info.json
  discord-frontend/hartex-discord-commands-spec/utilities-plugin/serverinfo.json
Labels: Bot: Enhancement

#1238 Use `info bot` Instead
  discord-frontend/hartex-discord-commands/src/general/latency.rs
  discord-frontend/hartex-discord-commands/src/general/mod.rs
  discord-frontend/hartex-discord-commands/src/general/uptime.rs
  discord-frontend/hartex-discord-commands/src/utilities/info/info_bot.rs
  discord-frontend/hartex-discord-commands/src/utilities/info/mod.rs
  discord-frontend/hartex-discord-worker/src/interaction.rs
  localization/locales/en-GB/discord-frontend/commands/general-plugin.ftl
  localization/locales/en-GB/discord-frontend/commands/utilities-plugin.ftl
Labels: Bot: Enhancement, Bot: Breaking Change

#1241 `/info bot`: Make `Bot Started` Localizable
  .idea/jsonSchemas.xml
  discord-frontend/hartex-discord-commands/src/utilities/info/info_bot.rs
  localization/locales/en-GB/discord-frontend/commands/utilities-plugin.ftl
Labels: Bot: Enhancement, Localization: Enhancement

#1242 Update zh-TW translation
  localization/locales/zh-TW/discord-frontend/commands/general-plugin.ftl
  localization/locales/zh-TW/discord-frontend/commands/utilities-plugin.ftl
Labels: Localization: Enhancement
