Repository TeamHarTex/HarTex, pull requests merged in 2023-08, with the labels that each got.

#1265 `/info bot`: Add Latency Information
  discord-frontend/hartex-discord-commands/src/utilities/info/info_bot.rs
  localization/locales/en-GB/discord-frontend/commands/utilities-plugin.ftl
Labels: Bot: Enhancement

#1271 Localization: Fallback to `en_GB`
  localization/hartex-localization-core/src/lib.rs
Labels: Localization: Bugfix

#1274 Cache: Update Role Things
  discord-frontend/hartex-discord-entitycache-cacheupdaters/src/guild_create.rs
  discord-frontend/hartex-discord-entitycache-entities/src/role.rs
  discord-frontend/hartex-discord-entitycache-repositories/src/role.rs
Labels: Bot: Enhancement

#1285 Rust: Enable Link-Time Optimization
  api-backend/Cargo.toml
  bors/Cargo.toml
  buildsystem/Cargo.toml
  discord-frontend/Cargo.toml
  localization/Cargo.toml
  rust-utilities/Cargo.toml
Labels: Bot: Enhancement, Buildsystem: Enhancement, Utilities: Enhancement, Localization: Enhancement, Backend: Enhancement, Bors: Enhancement

#1286 Cache: Fix Cache Updater for Guild Create
  discord-frontend/hartex-discord-entitycache-cacheupdaters/src/guild_create.rs
  discord-frontend/hartex-discord-entitycache-entities/src/role.rs
  discord-frontend/hartex-discord-entitycache-repositories/src/role.rs
Labels: Bot: Bugfix

#1288 Cache: Get Role Entity from Repository
  discord-frontend/hartex-discord-entitycache-repositories/src/role.rs
Labels: Bot: Enhancement

#1290 Cache: Get All Role IDs In Guild
  discord-frontend/Cargo.lock
  discord-frontend/hartex-discord-commands/src/utilities/info/info_bot.rs
  discord-frontend/hartex-discord-commands/src/utilities/info/mod.rs
  discord-frontend/hartex-discord-entitycache-cacheupdaters/src/guild_create.rs
  discord-frontend/hartex-discord-entitycache-entities/src/role.rs
  discord-frontend/hartex-discord-entitycache-repositories/Cargo.toml
  discord-frontend/hartex-discord-entitycache-repositories/src/role.rs
Labels: Bot: Enhancement

#1302 ``/info server`: Add Role Count
  api-backend/hartex-backend-routes-v1/src/bors.rs
  discord-frontend/hartex-discord-commands/src/utilities/info/info_server.rs
  discord-frontend/hartex-discord-entitycache-repositories/src/role.rs
  localization/locales/en-GB/discord-frontend/commands/utilities-plugin.ftl
  localization/locales/zh-CN/discord-frontend/commands/general-plugin.ftl
  localization/locales/zh-CN/discord-frontend/commands/utilities-plugin.ftl
  localization/locales/zh-TW/discord-frontend/commands/utilities-plugin.ftl
Labels: Bot: Enhancement

#1304 Fix: Localization Panic
  CHANGELOG.md
  localization/hartex-localization-core/src/lib.rs
  localization/hartex-localization-macros/src/expand_bundle_get.rs
  localization/hartex-localization-macros/src/expand_bundle_get_args.rs
Labels: Bot: Bugfix

#1305 feat(tr/ja): Japanese translations
  discord-frontend/hartex-discord-commands-spec/general-plugin/about.json
  discord-frontend/hartex-discord-commands-spec/general-plugin/contributors.json
  discord-frontend/hartex-discord-commands-spec/general-plugin/latency.json
  discord-frontend/hartex-discord-commands-spec/general-plugin/uptime.json
  discord-frontend/hartex-discord-commands-spec/utilities-plugin/info.json
  localization/locales/ja/discord-frontend/commands/general-plugin.ftl
  localization/locales/ja/discord-frontend/commands/utilities-plugin.ftl
Labels: Localization: Enhancement

#1306 feat(tr/ja): Utilities plugin role info
  localization/locales/ja/discord-frontend/commands/utilities-plugin.ftl
Labels: Localization: Enhancement

#1307 Fix: Tests for Localization Macros
  localization/hartex-localization-test/tests/expand/bundle_get.expanded.rs
  localization/hartex-localization-test/tests/expand/bundle_get_args.expanded.rs
Labels: Localization: Bugfix

#1308 8.10 zh-CN
  localization/locales/zh-CN/discord-frontend/commands/utilities-plugin.ftl
Labels: Localization: Enhancement

#1311 Fix: Actually Fix Localization Tests
  localization/hartex-localization-test/tests/expand/bundle_get.expanded.rs
  localization/hartex-localization-test/tests/expand/bundle_get_args.expanded.rs
Labels: Localization: Bugfix

#1313 missed a translation
  discord-frontend/hartex-discord-commands-spec/utilities-plugin/info.json
Labels: Localization: Enhancement

#1314 Info Command: `/info role` Specification
  discord-frontend/hartex-discord-commands-spec/utilities-plugin/info.json
Labels: Bot: Enhancement

#1315 Info Command: Add Role Command Branch
  discord-frontend/hartex-discord-commands/src/utilities/info/mod.rs
Labels: Bot: Enhancement

#1316 Update zh-TW translation
  discord-frontend/hartex-discord-commands-spec/utilities-plugin/info.json
Labels: Localization: Enhancement

#1317 feat(tr/ja): ultilities-plugin /info role
  discord-frontend/hartex-discord-commands-spec/utilities-plugin/info.json
Labels: Localization: Enhancement

#1325 Cache: Add `roles` to Member Entity
  discord-frontend/hartex-discord-entitycache-entities/src/member.rs
  discord-frontend/hartex-discord-entitycache-repositories/src/member.rs
Labels: Bot: Enhancement

#1328 `/info role`: Obtain Role From Cache
  api-backend/Cargo.lock
  discord-frontend/hartex-discord-commands/src/utilities/info/info_role.rs
Labels: Bot: Enhancement

#1334 Rust: Deprecate Old `#[derive(CommandMetadata)]` Macro
  api-backend/Cargo.lock
  api-backend/hartex-backend-driver/Cargo.toml
  api-backend/hartex-backend-models-v1/Cargo.toml
  api-backend/hartex-backend-models/Cargo.toml
  bors/Cargo.lock
  bors/hartex-bors-database/Cargo.toml
  bors/hartex-bors-github/Cargo.toml
  bors/hartex-bors-website/Cargo.toml
  buildsystem/Cargo.lock
  buildsystem/hartexbuild-hartexfile/Cargo.toml
  discord-frontend/Cargo.lock
  discord-frontend/hartex-discord-commands-macros/src/commandmetadata.rs
  discord-frontend/hartex-discord-commands-macros/src/lib.rs
  discord-frontend/hartex-discord-commands-manager/Cargo.toml
  discord-frontend/hartex-discord-commands/src/general/about.rs
  discord-frontend/hartex-discord-configuration-manifest/Cargo.toml
  discord-frontend/hartex-discord-worker/Cargo.toml
Labels: Bot: Enhancement, Bot: Breaking Change

#1377 Remove Unncessary `format!` Invocation
  discord-frontend/hartex-discord-commands-macros/src/commandmetadata.rs
  discord-frontend/hartex-discord-commands-macros/src/lib.rs
  localization/Cargo.lock
Labels: Bot: Enhancement

#1378 Cache: Update Role Entity
  discord-frontend/hartex-discord-entitycache-entities/src/role.rs
  discord-frontend/hartex-discord-entitycache-repositories/src/role.rs
Labels: Bot: Enhancement

#1381 `/info role`: Add Role Name Info
  discord-frontend/hartex-discord-commands/src/utilities/info/info_role.rs
  localization/locales/en-GB/discord-frontend/commands/utilities-plugin.ftl
Labels: Bot: Enhancement

#1385 Bors: Remove Usage of Deprecated API
  bors/hartex-bors-database/src/client.rs
Labels: Bors: Enhancement

#1386 `/info role`: Update Embed Format
  discord-frontend/hartex-discord-commands-core/src/traits.rs
  discord-frontend/hartex-discord-commands-macros/src/commandmetadata.rs
  discord-frontend/hartex-discord-commands/src/general/about.rs
  discord-frontend/hartex-discord-commands/src/general/contributors.rs
  discord-frontend/hartex-discord-commands/src/utilities/info/info_role.rs
  discord-frontend/hartex-discord-commands/src/utilities/info/mod.rs
  discord-frontend/hartex-discord-entitycache-repositories/src/member.rs
  discord-frontend/hartex-discord-entitycache-repositories/src/role.rs
  localization/locales/en-GB/discord-frontend/commands/utilities-plugin.ftl
Labels: Bot: Enhancement

#1388 `/info role`: Fix Role Colour Display
  discord-frontend/hartex-discord-commands/src/utilities/info/info_role.rs
  discord-frontend/hartex-discord-entitycache-entities/src/role.rs
  discord-frontend/hartex-discord-entitycache-repositories/src/role.rs
  localization/locales/en-GB/discord-frontend/commands/utilities-plugin.ftl
Labels: Bot: Enhancement

#1391 Localization: Add General Bundle
  localization/locales/en-GB/discord-frontend/general.ftl
Labels: Localization: Enhancement
