Repository TeamHarTex/HarTex, pull requests merged in 2024-01, with the labels that each got.

#1789 Make Clippy Happy
  discord-frontend/hartex-discord-leader/src/queue.rs
  discord-frontend/hartex-discord-leader/src/shards.rs
Labels: Bot: Enhancement

#1807 Fix All Tests
  api-backend/.cargo/config
  buildsystem/.cargo/config
  database-queries/.cargo/config
  discord-frontend/.cargo/config
  discord-frontend/hartex-discord-commands-test/tests/ui/expected_equal1.stderr
  discord-frontend/hartex-discord-commands-test/tests/ui/expected_literal1.stderr
  discord-frontend/hartex-discord-commands-test/tests/ui/unexpected_end_of_input1.stderr
  discord-frontend/hartex-discord-entitycache-entities/src/guild.rs
  discord-frontend/hartex-discord-entitycache-entities/src/member.rs
  discord-frontend/hartex-discord-entitycache-entities/src/role.rs
  discord-frontend/hartex-discord-entitycache-entities/src/user.rs
  discord-frontend/hartex-discord-entitycache-macros/src/entity.rs
  discord-frontend/hartex-discord-entitycache-test/tests/expand/guild_override.rs
  discord-frontend/hartex-discord-entitycache-test/tests/expand/user.rs
  discord-frontend/hartex-discord-entitycache-test/tests/ui/fail/does_not_exist_or_older_version.rs
  discord-frontend/hartex-discord-entitycache-test/tests/ui/fail/does_not_exist_or_older_version.stderr
  discord-frontend/hartex-discord-entitycache-test/tests/ui/fail/field_does_not_exist_or_older_version.rs
  discord-frontend/hartex-discord-entitycache-test/tests/ui/fail/field_does_not_exist_or_older_version.stderr
  discord-frontend/hartex-discord-entitycache-test/tests/ui/success_with_warn/ignore_non_string_expressions.rs
  discord-frontend/hartex-discord-leader/src/shards.rs
  localization/.cargo/config
  rust-utilities/.cargo/config
Labels: Bot: Enhancement

#1808 Add Impl Relations Block
  .vscode/settings.json
  discord-frontend/hartex-discord-entitycache-macros/src/entity.rs
  discord-frontend/hartex-discord-entitycache-test/tests/expand/guild_override.expanded.rs
  discord-frontend/hartex-discord-entitycache-test/tests/expand/user.expanded.rs
Labels: Bot: Enhancement

#1809 Cache Entities: Add Relations
  api-backend/Cargo.lock
  buildsystem/Cargo.lock
  database-queries/Cargo.lock
  discord-frontend/Cargo.lock
  discord-frontend/hartex-discord-entitycache-entities/src/guild.rs
  discord-frontend/hartex-discord-entitycache-entities/src/member.rs
  discord-frontend/hartex-discord-entitycache-entities/src/role.rs
  localization/Cargo.lock
  rust-utilities/Cargo.lock
Labels: Bot: Enhancement

#1815 Entity Macro: Generate Function Signatures
  api-backend/Cargo.lock
  buildsystem/Cargo.lock
  database-queries/Cargo.lock
  discord-frontend/Cargo.lock
  discord-frontend/hartex-discord-entitycache-entities/Cargo.toml
  discord-frontend/hartex-discord-entitycache-entities/src/guild.rs
  discord-frontend/hartex-discord-entitycache-entities/src/member.rs
  discord-frontend/hartex-discord-entitycache-entities/src/role.rs
  discord-frontend/hartex-discord-entitycache-macros/Cargo.toml
  discord-frontend/hartex-discord-entitycache-macros/src/entity.rs
  discord-frontend/hartex-discord-entitycache-test/Cargo.toml
  discord-frontend/hartex-discord-entitycache-test/tests/expand/guild_override.expanded.rs
  discord-frontend/hartex-discord-entitycache-test/tests/expand/user.expanded.rs
  rust-utilities/Cargo.lock
Labels: Bot: Enhancement, Bot: Feature

#1816 Entity Macro: `&self` Macro
  discord-frontend/hartex-discord-entitycache-macros/src/entity.rs
Labels: Bot: Enhancement, Bot: Feature

#1820 Entity Macro: Generate Some More Impls
  discord-frontend/hartex-discord-entitycache-entities/src/guild.rs
  discord-frontend/hartex-discord-entitycache-entities/src/member.rs
  discord-frontend/hartex-discord-entitycache-entities/src/role.rs
  discord-frontend/hartex-discord-entitycache-entities/src/user.rs
  discord-frontend/hartex-discord-entitycache-macros/src/entity.rs
Labels: Bot: Enhancement

#1822 Entity Macro: Add Impl from Database Query Objects
  api-backend/Cargo.lock
  buildsystem/Cargo.lock
  database-queries/Cargo.lock
  discord-frontend/Cargo.lock
  discord-frontend/hartex-discord-entitycache-macros/src/entity.rs
  discord-frontend/hartex-discord-entitycache-macros/src/lib.rs
  discord-frontend/hartex-discord-entitycache-macros/src/typeext.rs
  rust-utilities/Cargo.lock
Labels: Bot: Enhancement, Bot: Feature

#1823 Entity Macro: Finish Modifications
  discord-frontend/hartex-discord-entitycache-macros/src/entity.rs
Labels: Bot: Enhancement, Bot: Feature

#1825 Entity Macro: Fix Tests
  api-backend/Cargo.lock
  database-queries/Cargo.lock
  discord-frontend/Cargo.lock
  discord-frontend/hartex-discord-entitycache-test/tests/expand/guild_override.rs
  discord-frontend/hartex-discord-entitycache-test/tests/expand/user.rs
  discord-frontend/hartex-discord-entitycache-test/tests/ui/fail/does_not_exist_or_older_version.rs
  discord-frontend/hartex-discord-entitycache-test/tests/ui/fail/field_does_not_exist_or_older_version.rs
  discord-frontend/hartex-discord-entitycache-test/tests/ui/fail/field_does_not_exist_or_older_version.stderr
  discord-frontend/hartex-discord-entitycache-test/tests/ui/success_with_warn/ignore_non_string_expressions.rs
  rust-utilities/Cargo.lock
Labels: Bot: Enhancement

#1827 Info Server: Use `GuildEntity::members`
  discord-frontend/hartex-discord-commands/src/utilities/info/info_server.rs
  discord-frontend/hartex-discord-entitycache-macros/src/entity.rs
  discord-frontend/hartex-discord-entitycache-repositories/src/member.rs
Labels: Bot: Enhancement

#1829 User Entity: Convert from Query Type
  discord-frontend/hartex-discord-commands/src/utilities/info/info_server.rs
  discord-frontend/hartex-discord-entitycache-entities/src/member.rs
  discord-frontend/hartex-discord-entitycache-entities/src/user.rs
Labels: Bot: Enhancement, Bot: Feature

#1845 Lua Config: Add Parsing Test
  .idea/HarTex-rust-discord-bot.iml
  api-backend/Cargo.lock
  buildsystem/Cargo.lock
  database-queries/Cargo.lock
  discord-frontend/Cargo.lock
  discord-frontend/hartex-discord-configuration-luart/Cargo.toml
  discord-frontend/hartex-discord-configuration-luart/src/config/appearance.rs
  discord-frontend/hartex-discord-configuration-luart/src/config/dashboard.rs
  discord-frontend/hartex-discord-configuration-luart/src/config/mod.rs
  discord-frontend/hartex-discord-configuration-luart/src/lib.rs
  discord-frontend/hartex-discord-configuration-luart/tests/parse.rs
  localization/Cargo.lock
  rust-utilities/Cargo.lock
Labels: Bot: Enhancement, Bot: Feature

#1846 Lua Config: Complete Appearance Data Structure
  discord-frontend/hartex-discord-configuration-luart/src/config/appearance.rs
  discord-frontend/hartex-discord-configuration-luart/src/config/mod.rs
  discord-frontend/hartex-discord-configuration-luart/tests/parse.rs
Labels: Bot: Enhancement

#1853 Web: 2560px Responsiveness
  web-frontend/App.vue
  web-frontend/pages/index.vue
  web-frontend/uno.config.ts
Labels: Web: Enhancement

#1861 Tilting Tweaks
  web-frontend/components/Landing/Feature/Card.vue
Labels: Web: Enhancement

#1866 `/info server`: Add Server Verification Level Information
  discord-frontend/hartex-discord-commands/src/utilities/info/info_server.rs
  localization/locales/en-GB/discord-frontend/commands/utilities-plugin.ftl
  localization/locales/en-GB/discord-frontend/guild.ftl
  localization/locales/zh-CN/discord-frontend/guild.ftl
  rust-utilities/hartex-discord-utils/src/hyper.rs
  rust-utilities/hartex-discord-utils/src/lib.rs
  rust-utilities/hartex-discord-utils/src/localizable/discord/guild.rs
  rust-utilities/hartex-discord-utils/src/localizable/mod.rs
  rust-utilities/hartex-discord-utils/src/markdown.rs
  rust-utilities/hartex-errors/src/lib.rs
Labels: Bot: Enhancement

#1870 `/info server`: Add MFA Level
  api-backend/Cargo.lock
  buildsystem/Cargo.lock
  database-queries/Cargo.lock
  database-queries/generated/discord_frontend.rs
  database-queries/queries/discord_frontend/cached_guild_select_by_id.sql
  database-queries/queries/discord_frontend/cached_guild_upsert.sql
  discord-frontend/Cargo.lock
  discord-frontend/hartex-discord-commands/src/utilities/info/info_server.rs
  discord-frontend/hartex-discord-entitycache-entities/src/guild.rs
  discord-frontend/hartex-discord-entitycache-macros/src/entity.rs
  discord-frontend/hartex-discord-entitycache-repositories/src/guild.rs
  localization/Cargo.lock
  localization/locales/en-GB/discord-frontend/commands/utilities-plugin.ftl
  localization/locales/en-GB/discord-frontend/guild.ftl
  rust-utilities/Cargo.lock
  rust-utilities/hartex-discord-utils/src/localizable/discord/guild.rs
Labels: Bot: Enhancement

#1871 Localization: Change `Very High` to `Highest`
  localization/locales/en-GB/discord-frontend/guild.ftl
Labels: Localization: Enhancement

#1875 `/info server`: Add Explicit Content Filter
  .vscode/settings.json
  discord-frontend/hartex-discord-commands/src/utilities/info/info_server.rs
  localization/locales/en-GB/discord-frontend/commands/utilities-plugin.ftl
  localization/locales/en-GB/discord-frontend/general.ftl
  localization/locales/en-GB/discord-frontend/guild.ftl
  localization/locales/ja/discord-frontend/general.ftl
  localization/locales/ja/discord-frontend/guild.ftl
  localization/locales/zh-CN/discord-frontend/general.ftl
  localization/locales/zh-CN/discord-frontend/guild.ftl
  localization/locales/zh-TW/discord-frontend/general.ftl
  localization/locales/zh-TW/discord-frontend/guild.ftl
  rust-utilities/hartex-discord-utils/src/localizable/discord/guild.rs
Labels: Bot: Enhancement

#1883 Cache: Update `UserEntity`
  CHANGELOG.md
  database-queries/generated/discord_frontend.rs
  database-queries/queries/discord_frontend/cached_user_select_by_id.sql
  database-queries/queries/discord_frontend/cached_user_upsert.sql
  discord-frontend/hartex-discord-entitycache-entities/src/user.rs
  discord-frontend/hartex-discord-entitycache-macros/src/entity.rs
  discord-frontend/hartex-discord-entitycache-repositories/src/user.rs
Labels: Bot: Enhancement

#1887 Buildsystem: Welcome Back x.py
  .gitignore
  .vscode/settings.json
  CHANGELOG.md
  bootstrap/Cargo.lock
  bootstrap/Cargo.toml
  bootstrap/bootstrap.py
  bootstrap/builder.py
  bootstrap/cmdrunner.py
  bootstrap/src/bin/main.rs
  bootstrap/src/config/mod.rs
  bootstrap/src/lib.rs
  hartex.example.conf
  x.py
Labels: Buildsystem: Breaking Change

#1888 Update translation (zh-TW)
  localization/locales/zh-TW/discord-frontend/commands/utilities-plugin.ftl
  localization/locales/zh-TW/discord-frontend/guild.ftl
Labels: Localization: Enhancement

#1890 X.py Buildsystem: Add Locking and Configuration Path
  .vscode/settings.json
  bootstrap/Cargo.lock
  bootstrap/Cargo.toml
  bootstrap/src/bin/main.rs
  bootstrap/src/config/flags.rs
  bootstrap/src/config/mod.rs
  bootstrap/src/lib.rs
Labels: Buildsystem: Enhancement

#1904 X.py Buildsystem: Add Clippy and Update CI
  .github/workflows/lints.yml
  .github/workflows/tests.yml
  bootstrap/src/builder.rs
  bootstrap/src/steps/clippy.rs
  bootstrap/src/steps/mod.rs
Labels: CI: Enhancement

#1914 Remove Old Buildsystem
  .github/workflows/buildsystem.yml
  CHANGELOG.md
  HarTexfile
  buildsystem/.cargo/config
  buildsystem/Cargo.lock
  buildsystem/Cargo.toml
  buildsystem/hartexbuild-driver/Cargo.toml
  buildsystem/hartexbuild-driver/src/cmdline.rs
  buildsystem/hartexbuild-driver/src/commands/build.rs
  buildsystem/hartexbuild-driver/src/commands/clean.rs
  buildsystem/hartexbuild-driver/src/commands/lint.rs
  buildsystem/hartexbuild-driver/src/commands/mod.rs
  buildsystem/hartexbuild-driver/src/commands/test.rs
  buildsystem/hartexbuild-driver/src/commands/update.rs
  buildsystem/hartexbuild-driver/src/main.rs
  buildsystem/hartexbuild-hartexfile/Cargo.toml
  buildsystem/hartexbuild-hartexfile/src/lib.rs
  buildsystem/hartexbuild-hartexfile/src/spec/mod.rs
  buildsystem/hartexbuild-hartexfile/src/spec/project.rs
  buildsystem/rustfmt.toml
  tools/bootstrap/config/vscode-settings.json
Labels: Buildsystem: Breaking Change, Buildsystem: Enhancement
